services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    hostname: app
    container_name: app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:15
    hostname: db
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./initdb/userdata.csv:/docker-entrypoint-initdb.d/userdata.csv

volumes:
  postgres_data:
    driver: local
